"""Write README.md from output/metrics.json.

The README is generated so that a number in it cannot go stale. Nothing here
computes anything: if a figure is not in metrics.json it does not go in the
README. Prose that does not depend on a number lives in this file as prose.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def pct(x, places=1):
    return f"{100 * x:.{places}f} percent"


def num(x, places=1):
    return f"{100 * x:.{places}f}"


def interval(row, key="ci"):
    lo, hi = row[key]
    return f"{100 * lo:.1f} to {100 * hi:.1f}"


def find(rows, label):
    for row in rows:
        if row["label"] == label:
            return row
    raise KeyError(f"{label} is not in metrics.json, so it cannot go in the README")


def maybe(rows, label):
    try:
        return find(rows, label)
    except KeyError:
        return None


def agreement_table(rows):
    out = [
        "| configuration | agreement | 95 percent CI | comparisons scored |",
        "| --- | --- | --- | --- |",
    ]
    for row in sorted(rows, key=lambda r: -r["accuracy"]):
        if row["n"] == 0:
            continue
        out.append(f"| {row['label']} | {num(row['accuracy'])} | {interval(row)} | {row['n']} |")
    return "\n".join(out)


def build(m):
    data = m["dataset"]
    no_ties = m["agreement"]["no_ties"]
    with_ties = m["agreement"]["with_ties"]

    gpt4 = find(no_ties, "gpt-4 pairwise, one order")
    gpt4_swap = find(no_ties, "gpt-4 pairwise, swap averaged")
    gpt4_single = find(no_ties, "gpt-4 single answer grading")
    ceiling = find(no_ties, "human ceiling, one annotator vs the majority of the others")
    raw_ceiling = find(no_ties, "human to human ceiling")
    length = find(no_ties, "length baseline")
    coin = find(no_ties, "random baseline")

    position = m["position_bias"]["gpt-4 pairwise"]
    rerun = m["rerun_stability"]
    swap_mitigation = next(r for r in m["mitigations"] if r["mitigation"] == "gpt-4: swap averaging")
    self_pref = m["self_preference"]["gpt-4 judging gpt-4 responses"]
    control = m["self_preference"]["gpt-4 judging claude-v1 responses (control)"]
    verb_human = m["verbosity"]["human majority"]
    verb_gpt4 = m["verbosity"]["gpt-4 pairwise, one order"]

    local_rows = [r for r in no_ties if r["label"].startswith("local 3B")]
    has_local = bool(local_rows)

    parts = []
    parts.append(
        f"""# judge-reliability

**Across {data['comparisons']} human labelled MT-Bench comparisons, GPT-4 judging a
pair of answers agrees with the human majority {pct(gpt4['accuracy'])} of the time,
against a human ceiling of {pct(ceiling['accuracy'])} and a length only baseline that
reaches {pct(length['accuracy'])}. Reversing the order the two answers are shown in
flips the verdict on {pct(position['flip_rate'])} of comparisons, and swap averaging
recovers {num(swap_mitigation['delta'])} points of agreement, which is most of the gap
to the ceiling.**

The judge is good. It is also not better than a careful human, it is only
{num(gpt4['accuracy'] - length['accuracy'])} points better than a rule that reads none
of the text and always picks the longer answer, and its order sensitivity turns out to
be indistinguishable from its own run to run noise. Those three facts are the reason to
measure a judge rather than assume one.

![judge agreement against the human ceiling and the length baseline](output/figures/fig1_agreement.png)

## What this is

An LLM-as-judge is a measurement instrument, and nobody ships an instrument
without calibrating it. This repo calibrates one: agreement with human
preferences against the human to human ceiling, position bias, verbosity bias,
self preference, prompt sensitivity, cost, and which debiasing mitigations
actually recover accuracy rather than merely sounding sensible.

Every number below is regenerated by `make all` from cached judgments. No API
key, no model call, no network beyond the initial public data download.

## The data

- **{data['comparisons']} comparisons** from `lmsys/mt_bench_human_judgments`, CC BY 4.0:
  {data['human_votes']} individual votes from {data['annotators']} annotators over
  {data['questions']} MT-Bench questions and {len(data['models'])} models
  ({', '.join(data['models'])}), first and second conversation turns.
- **Human labels**: the annotator majority names a winner on
  {data['human_label_counts'].get('a', 0) + data['human_label_counts'].get('b', 0)}
  comparisons and ties on {data['human_label_counts'].get('tie', 0)}.
  {data['comparisons_with_2plus_annotators']} comparisons have two or more annotators,
  which is what makes a ceiling possible.
- **Judges**: GPT-4 (0613) pairwise in both presentation orders and GPT-4 single answer
  grading, both from the judgments LMSYS released with MT-Bench, plus a local
  Qwen2.5 3B run here on a laptop, plus two non LLM baselines.

## 1. Agreement, and the ceiling that gives it meaning

Ties excluded on both sides, which is the standard setup and the only one where a
judge, a human and a coin flip are comparable. `comparisons scored` is how many
of the {data['comparisons']} survive that restriction for each configuration:
a judge that abstains more is scored on fewer and easier comparisons.

{agreement_table(no_ties)}

Two ceilings, because the obvious one is unfair to humans. Annotator against
annotator is {pct(raw_ceiling['accuracy'])}, which is what people usually quote.
But a judge is scored against the *majority* of several annotators, a denoised
label, so the like for like number is one annotator against the majority of the
others: {pct(ceiling['accuracy'])} ({interval(ceiling)}). Quote the first and GPT-4
looks superhuman. Quote the second and it lands {num(ceiling['accuracy'] - gpt4['accuracy'])}
points short, and swap averaging closes that gap.

Cohen's kappa tells the same story with the chance agreement taken out:
{m['kappa']['gpt-4 pairwise, one order']['cohens_kappa']:.2f} for GPT-4 against
{m['kappa']['length baseline']['cohens_kappa']:.2f} for the length rule and
{m['kappa']['random baseline']['cohens_kappa']:.2f} for the coin. Krippendorff's alpha
over the {m['krippendorff']['n_raters']} human annotators is
{m['krippendorff']['humans_only']:.3f}; adding GPT-4 to the annotator pool moves it to
{m['krippendorff']['gpt-4 pairwise, one order']:.3f}. On this evidence GPT-4 is about as
agreeable as one more human annotator, no more and no less.

Same table, ties kept and counted as a third label:

{agreement_table(with_ties)}

## 2. Position bias, next to the judge's own noise

Every comparison is judged twice, once in each order.

![position bias flip rates](output/figures/fig2_position_bias.png)

- Order reversal flips the verdict on **{pct(position['flip_rate'])}**
  ({interval(position, 'flip_ci')}) of {position['n_comparisons']} comparisons.
- There is **no directional preference**: across
  {position['n_decided_presentations']} decided presentations the judge picks whichever
  answer was shown first {pct(position['position_one_rate'])} of the time. A coin does
  that. The bias is instability, not a thumb on the first position.
- GPT-4 single answer grading has no position bias at all, because it never sees
  the two answers together.

The number that puts the flip rate in perspective: {rerun['n_judgments']} of these
judgments exist twice in the released files, same prompt, same model, runs weeks
apart. GPT-4 agrees with itself on {pct(rerun['same_verdict_rate'])} of them, so it
**disagrees with itself {pct(1 - rerun['same_verdict_rate'])} of the time with nothing
changed at all**. The {pct(position['flip_rate'])} flip rate under order reversal is the
same size. Whatever swap averaging is buying here, it is variance reduction, not the
removal of a directional bias.

## 3. Verbosity

![how often each judge picks the longer answer](output/figures/fig3_verbosity.png)

GPT-4 picks the longer answer {pct(verb_gpt4['picks_longer_rate'])} of the time
(r = {verb_gpt4['corr_choice_lengthdiff']:.2f} between its choice and the length
difference). The humans pick the longer answer {pct(verb_human['picks_longer_rate'])} of
the time (r = {verb_human['corr_choice_lengthdiff']:.2f}). Those are the same number.

This is the finding people get backwards. The judge's correlation with length is
not by itself evidence of bias, because on this data longer answers really are
better and humans prefer them at the same rate. What it does establish is how low
the bar is: a rule that reads none of the text and always picks the longer answer
already agrees with humans {pct(length['accuracy'])} of the time, against a coin flip's
{pct(coin['accuracy'])}. Roughly {pct(length['accuracy'] / gpt4['accuracy'], 0)} of what a
frontier judge achieves is achievable by counting characters.
"""
    )

    padding = m.get("padding_test")
    if padding:
        parts.append(
            f"""
The controlled version holds quality fixed: pad the shorter answer with content
free filler until it is half again as long as the longer one, and see whether the
verdict moves. On {padding['n']} comparisons where the local judge preferred the other
answer before padding, it moved to the padded answer
**{pct(padding['moved_to_padded_rate'])}** of the time ({interval(padding)}).
"""
        )

    parts.append(
        f"""
## 4. Self preference

GPT-4 judging comparisons that include a GPT-4 response, against how the same
humans scored the same comparisons:

| | judge win rate for the family | human win rate | gap | 95 percent CI | comparisons |
| --- | --- | --- | --- | --- | --- |
| gpt-4 judging gpt-4 | {num(self_pref['judge_win_rate_for_family'])} | {num(self_pref['human_win_rate_for_family'])} | +{num(self_pref['difference'])} | {interval(self_pref)} | {self_pref['n']} |
| gpt-4 judging claude-v1 (control) | {num(control['judge_win_rate_for_family'])} | {num(control['human_win_rate_for_family'])} | +{num(control['difference'])} | {interval(control)} | {control['n']} |

GPT-4 rates its own family {num(self_pref['difference'])} points higher than the humans
do, more than three times the gap it shows for a family it has no stake in. The
interval excludes zero. It is a real effect on {self_pref['n']} comparisons, and it is
still one judge, one response set and one point in time, so read
`LIMITATIONS.md` before quoting it. It cannot be separated here from stylistic
kinship: GPT-4 may simply favour answers that look like its own.
"""
    )

    boards = m["leaderboards"]
    if has_local:
        local_boards = {k: v for k, v in boards.items() if k.startswith("local 3B")}
        tops = {k: v["top_model"] for k, v in local_boards.items()}
        taus = ", ".join(f"{k.split(', ')[1]} {v['kendall_tau_vs_human']:.2f}" for k, v in local_boards.items())
        best = max(local_rows, key=lambda r: r["accuracy"])
        worst = min(local_rows, key=lambda r: r["accuracy"])
        local_gpt4 = find(m["agreement_on_local_subsample"], "gpt-4 pairwise, one order")
        parts.append(
            f"""
## 5. Prompt sensitivity

The judge prompt is a free parameter that teams pick by taste. Here are three,
identical except for scaffolding, run by the same local Qwen2.5 3B model over the
same {data['local_judge_subsample']} comparisons: a bare instruction, a rubric with an
explicit warning about length and order, and a chain of thought prompt.

![model win rates by judge prompt](output/figures/fig4_prompt_sensitivity.png)

| judge prompt | agreement | 95 percent CI | comparisons scored |
| --- | --- | --- | --- |
"""
            + "\n".join(
                f"| {r['label'].replace('local 3B, ', '')} | {num(r['accuracy'])} | {interval(r)} | {r['n']} |"
                for r in sorted(local_rows, key=lambda r: -r["accuracy"])
            )
            + f"""

Changing nothing but the judge prompt moves agreement by
{num(best['accuracy'] - worst['accuracy'])} points, from {num(worst['accuracy'])} to
{num(best['accuracy'])}. Kendall tau between each prompt's model ranking and the human
ranking: {taus}. The model at the top of the leaderboard under each prompt:
{', '.join(f"{k.replace('local 3B, ', '')} picks {v}" for k, v in tops.items())}.

On the same {data['local_judge_subsample']} comparisons GPT-4 scores
{num(local_gpt4['accuracy'])}, so the gap between a frontier judge and a laptop judge is
real and large. What the local judge adds is the sensitivity measurement: it is
cheap enough to run under every prompt variant, which is the experiment a team
actually needs before trusting a leaderboard.
"""
        )
    else:
        parts.append(
            """
## 5. Prompt sensitivity

Not measured in this run: the local judge cache is empty. Run
`make judge` and then `make analysis`, or see USAGE.md to point the harness at a
model of your own.
"""
        )

    parts.append(
        """
## 6. Mitigations, measured rather than assumed

![mitigation effectiveness](output/figures/fig5_mitigations.png)

| mitigation | before | after | change | 95 percent CI | comparisons scored before and after |
| --- | --- | --- | --- | --- | --- |
"""
        + "\n".join(
            f"| {r['mitigation']} | {num(r['baseline_accuracy'])} | {num(r['mitigated_accuracy'])} | "
            f"{'+' if r['delta'] >= 0 else ''}{num(r['delta'])} | {interval(r)} | "
            f"{pct(r['coverage_before'], 0)} to {pct(r['coverage_after'], 0)} |"
            for r in m["mitigations"]
        )
        + f"""

Swap averaging is the one that works, and it is not free: it doubles the number
of model calls and it converts every order disagreement into a tie, so coverage
drops from {pct(swap_mitigation['coverage_before'], 0)} of comparisons to
{pct(swap_mitigation['coverage_after'], 0)}. You are buying accuracy with abstention as
much as with debiasing, which is fine as long as you know that is the trade.
"""
    )

    parts.append(
        """
## 7. Cost against reliability

![cost against reliability](output/figures/fig6_cost_reliability.png)

| judge | mean input tokens | mean output tokens | USD per 1000 judgments | median latency |
| --- | --- | --- | --- | --- |
"""
        + "\n".join(
            f"| {c['judge_id']} | {c['mean_input_tokens']:.0f} | {c['mean_output_tokens']:.0f} | "
            f"{c['usd_per_1000_judgments']:.2f}{' (estimated)' if c.get('token_counts_estimated') else ''} | "
            f"{c['median_latency_s']:.2f} s |" if "median_latency_s" in c else
            f"| {c['judge_id']} | {c['mean_input_tokens']:.0f} | {c['mean_output_tokens']:.0f} | "
            f"{c['usd_per_1000_judgments']:.2f}{' (estimated)' if c.get('token_counts_estimated') else ''} | not recorded |"
            for c in m["cost"]
        )
        + """

Token counts for the released GPT-4 judgments are estimated from character
counts and priced at gpt-4-0613 list prices, so treat that column as an order of
magnitude. Swap averaging doubles it.
"""
    )

    parts.append(
        f"""
## The unflattering findings, in one place

1. **Order sensitivity is not a bias, it is noise.** GPT-4 flips on
   {pct(position['flip_rate'])} of comparisons when the order is reversed, and disagrees
   with itself on {pct(1 - rerun['same_verdict_rate'])} of identical reruns. There is no
   directional preference for position one to remove
   ({pct(position['position_one_rate'])}, which is a coin). Swap averaging helps because
   averaging two noisy draws helps.
2. **The length baseline is closer than it should be.** Always preferring the
   longer answer agrees with humans {pct(length['accuracy'])} of the time, reaching
   {pct(length['accuracy'] / gpt4['accuracy'], 0)} of what GPT-4 achieves while reading
   none of the text. Any judge evaluation without this baseline in it is not
   telling you what the judge contributes.
3. **The judge is not better than a person.** {pct(gpt4['accuracy'])} against a like
   for like human ceiling of {pct(ceiling['accuracy'])}. The commonly quoted comparison,
   against raw annotator to annotator agreement of {pct(raw_ceiling['accuracy'])}, makes
   the judge look superhuman and is the wrong comparison.
4. **The judge is partial to itself**, by {num(self_pref['difference'])} points against
   the human labels on {self_pref['n']} comparisons, more than three times the gap for a
   family it has no stake in.
5. **The best scoring configuration scores best partly by abstaining.** GPT-4
   single answer grading reaches {pct(gpt4_single['accuracy'])}, the highest number in
   the repo, on {gpt4_single['n']} comparisons rather than {gpt4['n']}. Read coverage
   next to accuracy or that number is a mirage.

## Reproduce

```bash
pip install -r requirements.txt
make all
```

`make all` downloads the public data, audits it, rebuilds the comparison table,
loads the released GPT-4 judgments into the cache, runs the tests, and rewrites
every number above. `make analysis` on its own does everything from the committed
cache with no network at all.

To run a judge of your own, see [USAGE.md](USAGE.md). The harness needs one class
with one method.

## Files

| Path | What it is |
| --- | --- |
| `00_download.py` to `07_report.py` | the pipeline, in order |
| `harness/` | the reusable part: prompts, cache, judge backends, statistics |
| `data/judgments/` | every judge call, one JSON file per call, keyed by a hash of the prompt |
| `output/metrics.json` | every number in this README |
| `output/audit.md` | the data audit, run before anything is built on the data |
| `tests.py` | swap logic, bootstrap, kappa, cache key, verdict parsing |
| `DECISIONS.md` | what was decided and what it cost |
| `LIMITATIONS.md` | what these numbers do not support |

Data is `lmsys/mt_bench_human_judgments` (CC BY 4.0) and the judgments released
with MT-Bench by LMSYS. Figures use a colourblind checked palette; every bar
carries its value as text.
"""
    )
    return "".join(parts)


def main():
    with open(os.path.join(HERE, "output", "metrics.json"), encoding="utf-8") as fh:
        metrics = json.load(fh)
    text = build(metrics)
    if "—" in text or "–" in text:
        raise SystemExit("house rule: no dashes of that kind in the README")
    path = os.path.join(HERE, "README.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {path} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
